# Files

A file is any item that can be created, stored, or deleted by the user or operating system.

### CSV

`DataFrame.to_csv()` is used to write into a csv file.

`read_csv()` is used to read a csv file.

In [13]:
import numpy as np
import pandas as pd

In [14]:
csf_df = pd.DataFrame(np.random.randint(0, 100, (1000, 5)))

In [15]:
# Saving to a csv file
csf_df.to_csv("csv-dataframe.csv")

In [16]:
# Reading a CSV file
pd.read_csv("csv-dataframe.csv")

     Unnamed: 0   0   1   2   3   4
0             0  83   9  33  48  56
1             1  76  76  16  42  56
2             2  83  33  18  49  37
3             3  54  84  29  58  94
4             4  71  68  78  67  75
..          ...  ..  ..  ..  ..  ..
995         995   5  95  37  49  65
996         996  93  47   4  90  89
997         997  46  13  34  53  61
998         998  55  81  72   2  26
999         999  19  44  93  64  20

[1000 rows x 6 columns]

### Parquet
`DataFrame.to_parquet()` is used to write a parquet file.

`pandas.read_parquet()` is used to read a parquet file.

In [17]:
par_df = pd.DataFrame(np.random.randint(0, 100, (1000, 10)))

In [21]:
# Writing into a parquet file
par_df.to_parquet("par-data.parquet")

In [22]:
# Reading a parquet file
pd.read_parquet("par-data.parquet")

      0   1   2   3   4   5   6   7   8   9
0    81  15  57  80   7   7  96  89  72  77
1    26  97  87  11  92  58  46  40  77  41
2    27  96  51  15   4  31  56  13  82  76
3     6  55  20  62  70  41  28   1  44  67
4     9  30  71  63  41  52  13  75  42  89
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
995  86  12  94  79  57   5  33  84  49  10
996  86  98  11  52  94  79  77  15  89  30
997  63  76  21   3  37   1  68  88  64  11
998  27  45  95  97   2  15  39  56  94  91
999  36  87  49  67  92  38  95  24  68  40

[1000 rows x 10 columns]

### Excel
`DataFrame.to_excel()` is used to write into an excel file.

`read_excel()` is used to read from an Excel file.

In [24]:
excel_df = pd.DataFrame(np.random.randint(0, 100, (10000, 20)))

In [25]:
excel_df.to_excel("excel-raw-data.xlsx", sheet_name="Saved-From-Pandas")

In [26]:
pd.read_excel("excel-raw-data.xlsx", "Saved-From-Pandas", index_col=None, na_values=["NA"])

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
0,0,87,79,97,19,63,11,79,29,39,...,92,99,20,12,47,81,26,43,57,38
1,1,10,68,67,41,87,19,69,86,27,...,95,34,86,8,21,49,51,77,52,10
2,2,25,61,96,99,37,77,77,54,80,...,98,14,25,91,78,49,6,76,0,22
3,3,64,11,56,15,75,34,15,15,35,...,33,49,19,57,79,27,40,56,52,71
4,4,4,28,66,0,78,83,17,29,40,...,44,81,39,75,65,62,29,5,34,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,42,56,59,54,7,88,10,23,13,...,26,79,91,66,3,61,57,69,92,24
9996,9996,53,47,55,87,50,39,99,74,0,...,59,79,77,41,59,54,55,90,39,75
9997,9997,55,38,59,77,6,67,7,17,8,...,64,6,7,47,33,17,92,6,7,38
9998,9998,81,85,12,3,47,50,24,4,24,...,98,39,63,27,20,84,71,19,48,86
9999,9999,41,51,10,8,0,28,30,13,15,...,79,64,62,80,29,52,76,98,17,16